name: build-nodejs-cws-change-item-batch

on:
  workflow_dispatch:
  push:
    paths:
      - nodejs/cws-change-item-batch/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: nodejs/cws-change-item-batch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: nodejs/cws-change-item-batch # subdirectory
          file: nodejs/cws-change-item-batch/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhysin/nodejs-cws-change-item-batch:latest
