name: execute-nodejs-cws-change-item-batch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

permissions:
  contents: read

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull lhysin/nodejs-cws-change-item-batch:latest

      - name: Run Docker container
        run: docker run lhysin/nodejs-cws-change-item-batch:latest
          

