name: execute-nodejs-cws-change-item-batch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci
      working-directory: /nodejs/cws-change-item-batch

    - name: Start the application
      run: npm start
      working-directory: /nodejs/cws-change-item-batch